### ISSUE TITLE
(bug, Guidance2022.2.1.12-rc1): NSwag proxy generation generates a silent exception

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#141]
If you compile the Yarp and look at the output from the build, you will see this:

~~~
12>Executing file '..\Sdks\TestFlow.Yarp.Facade.Sdk\Generator\facade.nswag' with variables 'Configuration=Debug'...
13>[10:29:15 INF] Starting up
12>[10:29:15 INF] Starting up
13>[10:29:15 Program [Information] Start the Api process.
12>[10:29:15 Yarp.ReverseProxy.Configuration.ConfigProvider.ConfigurationConfigProvider [Information] Loading proxy data from config.
12>[10:29:15  [Fatal] Unhandled exception
12>System.InvalidOperationException: Unable to load or apply the proxy configuration.
12> ---> System.MissingMethodException: Method not found: 'Void System.Net.Http.SocketsHttpHandler.set_ActivityHeadersPropagator(System.Diagnostics.DistributedContextPropagator)'.
12>   at Yarp.ReverseProxy.Forwarder.ForwarderHttpClientFactory.CreateClient(ForwarderHttpClientContext context)
12>   at Yarp.ReverseProxy.Management.ProxyConfigManager.UpdateRuntimeClusters(IEnumerable`1 incomingClusters)
12>   at Yarp.ReverseProxy.Management.ProxyConfigManager.ApplyConfigAsync(IReadOnlyList`1 routes, IReadOnlyList`1 clusters)
12>   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
12>   --- End of inner exception stack trace ---
12>   at Yarp.ReverseProxy.Management.ProxyConfigManager.InitialLoadAsync()
12>   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
12>   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints, Action`1 configureApp)
12>   at Microsoft.AspNetCore.Builder.ReverseProxyIEndpointRouteBuilderExtensions.MapReverseProxy(IEndpointRouteBuilder endpoints)
12>   at Program.<Main>$(String[] args) in C:\PRJ\HappyFlow\TestFlow\BE\Yarp\TestFlow.Yarp.Host\Program.cs:line 274
~~~

The cause of this problem is most likely the same cause that caused us to add the "NSwag" environment variable setting when generating Sdk's.

This doesn't seem to affect the generated Sdk, but it's not tidy. In the generated code, the statement should be changed from:

~~~csharp
        app.MapReverseProxy();
~~~

to

~~~csharp
    if (!IsInvokedByNSwag())
        app.MapReverseProxy();
~~~

... provided that `IsInvokedByNSwag` is available.

**Comment by vvdb-architecture** [comment]
Still present in rc3
