### ISSUE TITLE
Error when generating the Sdk Client with nswag

### ISSUE THREAD

**Issue by umih** [GFlisch/Arc4u.Guidance.Doc#201]
**Describe the bug**
Error when generating the Yarp Sdk Client

**To Reproduce**
1. Create a new test project with Guidance version 2022.2.1.13
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/31067425/7180ecd6-12be-42ad-a0d3-53fad0910da6)

2. Compiling it i noticed that the Sdk Client generation with nswag doesn't work for me.
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/31067425/627eb578-c761-41ac-b6e3-fab243738814)

3. Running the command from command line i get more details about the error
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/31067425/0227cc21-a713-4b67-b962-a57438f26006)

4. The  code found in the Yarp.HOST is triggering the Client generation
 
<Target Name="NSwagFacade" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">    <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development;NSwag=true" Command="$(NSwagExe_Net60) run ..\Sdks\Arc4uSeptember23Edition.Yarp.Facade.Sdk\Generator\facade.nswag  /variables:Configuration=$(Configuration)" />
  </Target>

Here is the complete error
 
System.InvalidOperationException: NSwag requires the assembly Arc4uSeptember23Edition.Yarp.Host, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null to have either an BuildWebHost or CreateWebHostBuilder/CreateHostBuilder method. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x for suggestions on ways to refactor your startup type.
   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 87
   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.GetServiceProvider(AssemblyLoader assemblyLoader) in /_/src/NSwag.Commands/Commands/Generation/OpenApiGeneratorCommandBase.cs:line 313
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunIsolatedAsync(AssemblyLoader assemblyLoader) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 323
   at NSwag.Commands.IsolatedCommandBase`1.IsolatedCommandAssemblyLoader.Run(String commandType, String commandData, String[] assemblyPaths, String[] referencePaths) in /_/src/NSwag.Commands/Commands/IsolatedCommandBase.cs:line 76
   at NSwag.Commands.IsolatedCommandBase`1.RunIsolatedAsync(String configurationFile) in /_/src/NSwag.Commands/Commands/IsolatedCommandBase.cs:line 61
   at NSwag.Commands.IsolatedSwaggerOutputCommandBase`1.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/IsolatedSwaggerOutputCommandBase.cs:line 51
   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 98
   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275
   at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61
 

**Desktop (please complete the following information):**
 - Visual Studio Version 17.5.3
 - Guidance Version 2022.2.1.13

**Comment by rdarko** [comment]
Can you please retest this and confirm if its still a problem.

**Comment by umih** [comment]
Error was generated due to missing certificate.

Solved problem by generating own certificate, here a [short ](https://github.com/GFlisch/Arc4u/blob/master/src/Arc4u.Standard.UnitTest/Decryptor/Generate%20a%20Certificate.txt) description on how to do it.

Then change the default certificate name from the config files with the own generated certificate name, then everything works.
