### ISSUE TITLE
(Guidance 2022.2.1.14)  Generated Blazor application obtains incorrect access token

### ISSUE THREAD

**Issue by vvdb-architecture** [GFlisch/Arc4u.Guidance.Doc#231]
After generating and registering a Blazor application, going to the "about" page to call the EnvironmentController on back-end fails with the following message in the browser console:

~~~
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The HTTP status code of the response was not expected (401).
      
      Status: 401
      Response: 
      
HTTP Response: 



EG.HappyFlow.Yarp.Facade.Sdk.RestException: The HTTP status code of the response was not expected (401).

Status: 401
Response: 

   at EG.HappyFlow.Yarp.Facade.Sdk.EnvironmentClient.GetAsync(CancellationToken cancellationToken) in C:\PRJ\HappyFlow\HappyFlow\BE\Yarp\Sdks\HappyFlow.Yarp.Facade.Sdk\HappyFlowYarpFacadeClient.cs:line 159
   at EG.HappyFlow.Blazor.Pages.About.OnInitializedAsync() in C:\PRJ\HappyFlow\HappyFlow\FE\Blazor\HappyFlow.Blazor\Pages\About.razor:line 49
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
~~~

When investigating the detailed error, the Yarp back-end raises the `ChallengeAsync` event with the following error:

~~~
{"IDX10214: Audience validation failed. Audiences: 'microsoft:identityserver:3c2538bf-25f7-4276-8a97-126278fe2dd6'. Did not match: validationParameters.ValidAudience: 'null' or validationParameters.ValidAudiences: 'https://happyflow.development.host'."}
~~~

The root cause is the fact that the Blazor application sends a bearer token containing an incorrect audience claim (Guid redacted):

~~~json
  "aud": "microsoft:identityserver:12345678-1234-1234-1234-123456789ABC",
~~~

The reason is because Blazor is generated with MSAL instead of the neutral     `<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.0" />`

This is a regression from the previous Guidance.

**Comment by vvdb-architecture** [comment]
Corrected in the latest version of the Guidance as of 21/2/2024
