### ISSUE TITLE
OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by Guy-Heylens-Elia** [GFlisch/Arc4u.Guidance.Doc#245]
**Information**
If the bug is linked to the Arc4u framework, please go to the [Arc4u repo](https://github.com/GFlisch/Arc4u/issues).

**Describe the bug**
When creating a new Solution in a blank project I get this error: 
OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation.
 

**To Reproduce**
1. Create blank solution in Visual Studio Prof 2022
2. Right click Solution and select "Create Arc4u AspNetCore Solution => 2022.2.1 "
3. Nothing happens
4. Output screen shows error: Error: 21/06/2024 11:30:43 Utc : OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation.

**Expected behavior**
A new Arc4u Solution is added like mentioned in TMD docs
**Screenshots**
![image](https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/104833610/5ed824c2-712e-476a-af1f-0b0a1e27b1eb)

**Desktop (please complete the following information):**
 - Visual Studio Pro 2022 ( 17.8.2 )
 - Guidance Version 2022.2.1.14 

**Additional context**
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Dev4u.LicManager.Core.Interface.Sdk.AssetV1Client.ProcessResponse(HttpClient client, HttpResponseMessage response)
   at Dev4u.LicManager.Core.Interface.Sdk.AssetV1Client.<GetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore2022_2.Services.ContentService.<>c__DisplayClass9_0.<<GetContentAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore2022_2.Services.ContentService.<GetContentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore2022_2.Services.ContentService.<GetStringContentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore2022_2.Services.ContentService.<GetConfigsAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore2022_2.Services.VersionPolicy.<GetConfigAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore.Commands.CreateSolutionCommand.<OnExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GuidanceCore.Commands.BaseGuidanceCommand`1.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Community.VisualStudio.Toolkit.BaseCommand.<>c__DisplayClass8_0.<<Execute>b__0>d.MoveNext()

**Comment by GFlisch** [comment]
Hi. Probably an error linked to your license. A new update of the backend and the guidance will give a better message in the future. Check your mail, if you have received an email from ***@***.*** with your license key and check you don't have a blank at the end when you do a copy paste of the license.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Guy Heylens ***@***.***>
Sent: Friday, June 21, 2024 1:51:32 PM
To: GFlisch/Arc4u.Guidance.Doc ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GFlisch/Arc4u.Guidance.Doc] OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation. (Issue #245)


Information
If the bug is linked to the Arc4u framework, please go to the Arc4u repo<https://github.com/GFlisch/Arc4u/issues>.

Describe the bug
When creating a new Solution in a blank project I get this error:
OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation.

To Reproduce
Steps to reproduce the behavior:

  1.  Create blank solution in Visual Studio Prof 2022
  2.  Right click Solution and select "Create Arc4u AspNetCore Solution => 2022.2.1 "
  3.  Nothing happens
  4.  Output screen shows error: Error: 21/06/2024 11:30:43 Utc : OnAfterOpenSolutionAsync => Attempted to perform an unauthorized operation.

Expected behavior
A new Arc4u Solution is added like mentioned in TMD docs
Screenshots
If applicable, add screenshots to help explain your problem.
image.png (view on web)<https://github.com/GFlisch/Arc4u.Guidance.Doc/assets/104833610/5ed824c2-712e-476a-af1f-0b0a1e27b1eb>

Desktop (please complete the following information):

  *   Visual Studio Pro 2022 ( 17.8.2 )
  *   Guidance Version 2022.2.1.14

Additional context
Add any other context about the problem here.

**Comment by rdarko** [comment]
Hello, can you please check if this is fixed on the 2022.2.1.16?
Thanks!
